# Generated by Django 4.0.4 on 2022-06-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_sample_alter_orderdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Пример работы', 'verbose_name_plural': 'Примеры работ'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='category',
            field=models.CharField(choices=[('Реверсивный инжиниринг', 'Реверсивный инжиниринг'), ('Конструкторская документация', 'Конструкторская документация'), ('3д моделирование/визуализация', '3д моделирование/визуализация')], max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
